name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run unit tests
        run: ./gradlew app:test

      - name: Run detekt tests
        run: ./gradlew app:detekt
